// <auto-generated />
using API_Practice.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_Practice.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API_Practice.Models.Emp", b =>
                {
                    b.Property<int>("eid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("eid"));

                    b.Property<string>("ename")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("esalary")
                        .HasColumnType("float");

                    b.Property<int>("mid")
                        .HasColumnType("int");

                    b.HasKey("eid");

                    b.HasIndex("mid");

                    b.ToTable("emps");
                });

            modelBuilder.Entity("API_Practice.Models.Manager", b =>
                {
                    b.Property<int>("mid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("mid"));

                    b.Property<string>("mname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("mid");

                    b.ToTable("manager");
                });

            modelBuilder.Entity("API_Practice.Models.Emp", b =>
                {
                    b.HasOne("API_Practice.Models.Manager", "manager")
                        .WithMany("emp")
                        .HasForeignKey("mid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("manager");
                });

            modelBuilder.Entity("API_Practice.Models.Manager", b =>
                {
                    b.Navigation("emp");
                });
#pragma warning restore 612, 618
        }
    }
}
